function otroerrors() {
    errors();
}

const errors = ()=>{
    return 3+z;
}

try{
    errors();
}catch(err){
    console.error('se rompi algo por ahi');
    console.error(err.message)
}
